### PR TITLE
feat: new look

### PR DESCRIPTION
**Pull request by smakosh**
## What's new?
- Fresh new look of the podcast
- Used [Simple cast Gatsby theme](https://github.com/vojtaholik/gatsby-theme-simplecast)

## Before you merge
- Make sure to add the env variables to the platform you're deploying the website to
> I highly recommend you switch to [Vercel](https://vercel.com) as it lets you easily switch the build commands just by choosing that this is using Gatsby

### CODE REVIEW

**Comment by smakosh** [comment]
https://gph.is/22XMJr1

**Comment by omarhoumz** [comment]
I think if you add a `build` script in the package.json file, the netlify build won't fail

**Comment by smakosh** [comment]
> I think if you add a `build` script in the package.json file, the netlify build won't fail

si @JefferyHus darbha bn3ass, he just needs to add the missing env variables as I mentioned on the PR's description

**Comment by JefferyHus** [comment]
Wayeh a ba @smakosh, I will spare some time to look into it

**Pull request closed without merging**
